"""empty message

Revision ID: 0d3edecda42a
Revises: b02326d715bb
Create Date: 2025-07-25 17:14:39.382361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3edecda42a'
down_revision: Union[str, Sequence[str], None] = 'b02326d715bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_first_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_var_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reading_var_id'], ['reading_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_second_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_var_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reading_var_id'], ['reading_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_third_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('reading_var_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reading_var_id'], ['reading_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_first_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_first_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_first_task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_first_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_second_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_second_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_second_task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_second_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_third_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_third_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_third_task_options')
    op.drop_table('reading_second_task_questions')
    op.drop_table('reading_second_task_options')
    op.drop_table('reading_first_task_questions')
    op.drop_table('reading_first_task_options')
    op.drop_table('reading_third_tasks')
    op.drop_table('reading_second_tasks')
    op.drop_table('reading_first_tasks')
    op.drop_table('reading_tasks')
    # ### end Alembic commands ###
