"""empty message

Revision ID: 278e0a193f2a
Revises: 6bfde6671111
Create Date: 2025-07-20 19:15:55.751616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278e0a193f2a'
down_revision: Union[str, Sequence[str], None] = '6bfde6671111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_first_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_second_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_third_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_bool_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct_anser', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_second_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_first_task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_first_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_first_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_third_task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_third_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['listening_third_task_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('listening_tasks_type_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_tasks_type_one',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_tasks_type_one_pkey'))
    )
    op.drop_table('listening_options')
    op.drop_table('listening_third_task_questions')
    op.drop_table('listening_pictures')
    op.drop_table('listening_first_task_questions')
    op.drop_table('listening_bool_options')
    op.drop_table('listening_third_tasks')
    op.drop_table('listening_tasks')
    op.drop_table('listening_second_tasks')
    op.drop_table('listening_first_tasks')
    # ### end Alembic commands ###
