"""empty message

Revision ID: 3399669a869f
Revises: 91120cb43628
Create Date: 2025-07-14 18:29:18.120660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3399669a869f'
down_revision: Union[str, Sequence[str], None] = '91120cb43628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_tasks_type_one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chars', sa.String(), nullable=False),
    sa.Column('correct_sentence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_tasks_type_two',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(), nullable=False),
    sa.Column('correct_char', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_tasks_type_two')
    op.drop_table('writing_tasks_type_one')
    # ### end Alembic commands ###
