"""empty message

Revision ID: 42d21f853d18
Revises: b96b2ec2e5a8
Create Date: 2025-07-23 19:30:32.370591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d21f853d18'
down_revision: Union[str, Sequence[str], None] = 'b96b2ec2e5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_first_tasks', sa.Column('listening_var_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'listening_first_tasks', 'listening_tasks', ['listening_var_id'], ['id'])
    op.add_column('listening_second_tasks', sa.Column('listening_var_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'listening_second_tasks', 'listening_tasks', ['listening_var_id'], ['id'])
    op.add_column('listening_third_tasks', sa.Column('listening_var_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'listening_third_tasks', 'listening_tasks', ['listening_var_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listening_third_tasks', type_='foreignkey')
    op.drop_column('listening_third_tasks', 'listening_var_id')
    op.drop_constraint(None, 'listening_second_tasks', type_='foreignkey')
    op.drop_column('listening_second_tasks', 'listening_var_id')
    op.drop_constraint(None, 'listening_first_tasks', type_='foreignkey')
    op.drop_column('listening_first_tasks', 'listening_var_id')
    # ### end Alembic commands ###
