"""empty message

Revision ID: 5d45a4fecb6a
Revises: 91616de00072
Create Date: 2025-07-11 20:16:57.897198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d45a4fecb6a'
down_revision: Union[str, Sequence[str], None] = '91616de00072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_tasks_type_three', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_tasks_type_three', 'description')
    # ### end Alembic commands ###
