"""empty message

Revision ID: 6d27b12d0795
Revises: 5d45a4fecb6a
Create Date: 2025-07-11 20:38:18.837156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d27b12d0795'
down_revision: Union[str, Sequence[str], None] = '5d45a4fecb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_questions', sa.Column('task_one_id', sa.Integer(), nullable=True))
    op.add_column('reading_questions', sa.Column('task_two_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reading_questions', 'reading_tasks_type_one', ['task_one_id'], ['id'])
    op.create_foreign_key(None, 'reading_questions', 'reading_tasks_type_two', ['task_two_id'], ['id'])
    op.drop_column('reading_questions', 'task_type')
    op.drop_column('reading_questions', 'task_id')
    op.add_column('sentence_options', sa.Column('task_one_id', sa.Integer(), nullable=True))
    op.add_column('sentence_options', sa.Column('task_two_id', sa.Integer(), nullable=True))
    op.add_column('sentence_options', sa.Column('task_three_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentence_options', 'reading_tasks_type_three', ['task_three_id'], ['id'])
    op.create_foreign_key(None, 'sentence_options', 'reading_tasks_type_one', ['task_one_id'], ['id'])
    op.create_foreign_key(None, 'sentence_options', 'reading_tasks_type_two', ['task_two_id'], ['id'])
    op.drop_column('sentence_options', 'task_type')
    op.drop_column('sentence_options', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentence_options', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sentence_options', sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sentence_options', type_='foreignkey')
    op.drop_constraint(None, 'sentence_options', type_='foreignkey')
    op.drop_constraint(None, 'sentence_options', type_='foreignkey')
    op.drop_column('sentence_options', 'task_three_id')
    op.drop_column('sentence_options', 'task_two_id')
    op.drop_column('sentence_options', 'task_one_id')
    op.add_column('reading_questions', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reading_questions', sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reading_questions', type_='foreignkey')
    op.drop_constraint(None, 'reading_questions', type_='foreignkey')
    op.drop_column('reading_questions', 'task_two_id')
    op.drop_column('reading_questions', 'task_one_id')
    # ### end Alembic commands ###
