"""empty message

Revision ID: 77ff1f4b11e3
Revises: d6b365bb4e41
Create Date: 2025-07-14 15:23:04.622344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ff1f4b11e3'
down_revision: Union[str, Sequence[str], None] = 'd6b365bb4e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_tasks_type_three', sa.Column('correct_answer_letter', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_tasks_type_three', 'correct_answer_letter')
    # ### end Alembic commands ###
