"""empty message

Revision ID: 7c1e6347304f
Revises: a6af3e96ea49
Create Date: 2025-07-22 20:33:44.009109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1e6347304f'
down_revision: Union[str, Sequence[str], None] = 'a6af3e96ea49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening_third_task_questions')
    op.add_column('listening_options', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('listening_options_question_id_fkey'), 'listening_options', type_='foreignkey')
    op.create_foreign_key(None, 'listening_options', 'listening_third_tasks', ['task_id'], ['id'])
    op.drop_column('listening_options', 'question_id')
    op.add_column('listening_third_tasks', sa.Column('correct_letter', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_third_tasks', 'correct_letter')
    op.add_column('listening_options', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listening_options', type_='foreignkey')
    op.create_foreign_key(op.f('listening_options_question_id_fkey'), 'listening_options', 'listening_third_task_questions', ['question_id'], ['id'])
    op.drop_column('listening_options', 'task_id')
    op.create_table('listening_third_task_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('correct_letter', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_third_tasks.id'], name=op.f('listening_third_task_questions_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_third_task_questions_pkey'))
    )
    # ### end Alembic commands ###
