"""empty message

Revision ID: 7d23c2e268c7
Revises: 61636441ccd5
Create Date: 2025-07-21 20:06:42.200001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d23c2e268c7'
down_revision: Union[str, Sequence[str], None] = '61636441ccd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening_pictures')
    op.add_column('listening_first_tasks', sa.Column('picture_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_first_tasks', 'picture_id')
    op.create_table('listening_pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('picture_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('letter', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_first_tasks.id'], name=op.f('listening_pictures_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_pictures_pkey'))
    )
    # ### end Alembic commands ###
