"""empty message

Revision ID: 801a4b6f4f93
Revises: cb12b330c567
Create Date: 2025-07-17 18:54:28.218789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801a4b6f4f93'
down_revision: Union[str, Sequence[str], None] = 'cb12b330c567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('listening_tasks_type_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_tasks_type_one',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_tasks_type_one_pkey'))
    )
    op.drop_table('listening_options')
    # ### end Alembic commands ###
