"""empty message

Revision ID: a6af3e96ea49
Revises: 7d23c2e268c7
Create Date: 2025-07-22 19:03:18.131572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6af3e96ea49'
down_revision: Union[str, Sequence[str], None] = '7d23c2e268c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening_bool_options')
    op.add_column('listening_second_tasks', sa.Column('text', sa.String(), nullable=False))
    op.add_column('listening_second_tasks', sa.Column('is_correct', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_second_tasks', 'is_correct')
    op.drop_column('listening_second_tasks', 'text')
    op.create_table('listening_bool_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_anser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_second_tasks.id'], name=op.f('listening_bool_options_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_bool_options_pkey'))
    )
    # ### end Alembic commands ###
