"""empty message

Revision ID: ab5732f4832a
Revises: f13c22a562ce
Create Date: 2025-07-24 20:38:43.410300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5732f4832a'
down_revision: Union[str, Sequence[str], None] = 'f13c22a562ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_third_task_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_letter', sa.String(length=1), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_third_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('listening_third_tasks', 'correct_letter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_third_tasks', sa.Column('correct_letter', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_table('listening_third_task_questions')
    # ### end Alembic commands ###
