"""empty message

Revision ID: b96b2ec2e5a8
Revises: a6af3e96ea49
Create Date: 2025-07-23 18:11:32.449247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96b2ec2e5a8'
down_revision: Union[str, Sequence[str], None] = 'a6af3e96ea49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_third_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['listening_third_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('listening_options')
    op.add_column('listening_third_tasks', sa.Column('correct_letter', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_third_tasks', 'correct_letter')
    op.create_table('listening_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('listening_options_pkey'))
    )
    op.drop_table('listening_third_task_options')
    # ### end Alembic commands ###
